<?php
$helper = $this->helper('mercadopago');

$grant_total = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
$coupon_mercadopago = Mage::getStoreConfig('payment/mercadopago_custom/coupon_mercadopago') == 1 ? 'true' : 'false';
$country = Mage::getStoreConfig('payment/mercadopago/country');
$_code = $this->getMethodCode();
$debugMode = Mage::getStoreConfigFlag('payment/mercadopago/debug_mode') == 1 ? 'true' : 'false';

$customer = $this->getCustomerAndCards();
$public_key = Mage::getStoreConfig(MercadoPago_Core_Helper_Data::XML_PATH_PUBLIC_KEY);

//@Gateway_Mode
$modeGateway = Mage::getStoreConfigFlag('payment/mercadopago_custom/enable_gateway') == 1 ? 'true' : 'false';

$customer_session = Mage::getSingleton('customer/session')->getCustomer();
$payer_email = $customer_session->getEmail();

// $route = $this->getRequest()->getRequestedRouteName();
$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true);


$credit_card = array();
$debit_card = array();
$customer_cards = array();
$currency_ratio = 1;
$woocommerce_currency = 2;
$account_currency = 3;
$amount = 200;
$customerId = 32;

$accessToken = Mage::getStoreConfig(MercadoPago_Core_Helper_Data::XML_PATH_ACCESS_TOKEN);
$mp = Mage::helper('mercadopago')->getApiInstance($accessToken);
$paymentMethods = $mp->get_payment_methods();

$creditCards = array();
$debitCards = array();
$prepaidCards = array();

if ($paymentMethods['status'] == 200) {
    foreach ($paymentMethods['response'] as $method) {
        if ($method['payment_type_id'] == 'credit_card') {
            $creditCards[] = $method;
        }

        if ($method['payment_type_id'] == 'debit_card') {
            $debitCards[] = $method;
        }

        if ($method['payment_type_id'] == 'prepaid_card') {
            $prepaidCards[] = $method;
        }
    }
}

?>
<script type="text/javascript">
    if (typeof sendAnalyticsData === 'function') {
        sendAnalyticsData("<?php echo $_code ?>");
    }
    $("mp-frame-payments").toggle();
</script>


<style>
    #mpCouponCode {
        width: calc(100% - 15px) !important;
    }

    .mp-frame-links-1 {
        float: left;
    }

    @media screen and (max-width: 320px) {
        .mp-col-md-9, .mp-col-md-3, .mp-col-md-6 {
            width: 100% !important;
        }

        .mp-pr-15 {
            padding-right: 0 !important;
        }

        .mp-col-md-2 {
            width: 40%;
        }

        .mp-col-md-4 {
            width: 60%;
        }

        .mp-frame-links-1 {
            margin-top: 10px;
        }

        #mp_promotion_link {
            display: none;
        }

        #mp_checkout_link {
            padding-left: 0 !important;
        }

        #mpCouponCode {
            width: 100% !important;
        }

        #mpDocType {
            width: calc(100% - 15px) !important;
        }

        #mpApplyCoupon {
            margin-top: 15px;
            padding-right: 0;
        }

        #mpDocType {
            margin-right: 15px;
        }
    }
</style>

<ul class="form-list form-mercadopago" id="payment_form_<?php echo $_code ?>" style="display: none;">
    <li class="card-form first-card">
        <div id="mp_checkout_object_fit">
            <div class="mp_checkout_center">
                <div class="mp-panel-custom-checkout">
                    <!--                    Info-->
                    <div class="mp-row-checkout">
                        <div class="mp_checkout_installments_warning mp_checkout_float_left">
                            <?php echo $helper->__('Hasta XX Cuotas'); ?>
                        </div>
                        <div class="mp-frame-links">
                            <div class="mp-frame-links-1">
                                <a class="mp-checkout-link mp-pr-10"
                                   id="mp-button-show-payments"
                                   onclick="taxToggle('mp-frame-payments', 'mp-frame-payments', 'mp-tarjetas-opened');">
                                    <?php echo $helper->__('With what cards can I pay'); ?> ⌵</a>
                                <span id="mp_promotion_link"> | </span>
                            </div>

                            <div class="mp-frame-links-1">
                                <a href="https://www.mercadopago.com.ar/cuotas" id="mp_checkout_link"
                                   class="mp-checkout-link mp-pl-10"
                                   target="_blank"><?php echo $helper->__('See current promotions'); ?></a>
                            </div>
                        </div>
                    </div>
                    <!--                    Card Images Details-->
                    <div class="mp-row-checkout">
                        <div class="mp-frame-payments" id="mp-frame-payments">

                            <?php if (count($creditCards) != 0) : ?>
                                <div class="mp-col-md-12">
                                    <div class="mp-frame-tarjetas">
                                        <p class="submp-title-checkout-custom">
                                            <?php echo $helper->__('Credit cards') ?>
                                        </p>

                                        <?php foreach ($creditCards as $credit_image) : ?>
                                            <img src="<?php echo $credit_image['secure_thumbnail'] ?>"
                                                 class="mp-img-fluid mp-img-tarjetas" alt=""/>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <?php if (count($debitCards) != 0) : ?>
                                <div class="mp-col-md-12">
                                    <div class="mp-frame-tarjetas">
                                        <p class="submp-title-checkout-custom mp-pt-10">
                                            <?php echo $helper->__('Debit card') ?>
                                        </p>
                                        <?php foreach ($debitCards as $debit_image) : ?>
                                            <img src="<?= $debit_image['secure_thumbnail'] ?>"
                                                 class="mp-img-fluid mp-img-tarjetas" alt=""/>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>

                            <?php if (count($prepaidCards) != 0) : ?>
                                <div class="mp-col-md-12">
                                    <div class="mp-frame-tarjetas">
                                        <p class="submp-title-checkout-custom">
                                            <?php echo $helper->__('Prepaid Card') ?>
                                        </p>

                                        <?php foreach ($prepaidCards as $pre_card) : ?>
                                            <img src="<?php echo $pre_card['secure_thumbnail'] ?>"
                                                 class="mp-img-fluid mp-img-tarjetas" alt=""/>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>

                    <!--                    Discount-->
                    <div class="mp-row-checkout">
                        <div class="mp-col-md-12" id="mercadopago-form-coupon">
                            <div class="mp-frame-tarjetas mp-text-justify">
                                <p class="mp-subtitle-custom-checkout">
                                    <?php echo $helper->__('Enter your discount coupon'); ?>
                                </p>
                                <div class="mp-row-checkout mp-pt-10">
                                    <div class="mp-col-md-9">
                                        <input type="text" class="mp-form-control" id="mpCouponCode"
                                               name="mercadopago_custom[coupon_code]" autocomplete="off" maxlength="24"
                                               placeholder="<?php echo $helper->__('Enter your coupon'); ?>"/>
                                    </div>
                                    <div class="mp-col-md-3">
                                        <input type="button" class="mp-button mp-pointer" id="mpApplyCoupon"
                                               value="<?php echo $helper->__('Apply'); ?>">
                                    </div>
                                </div>
                                <span class="mp-discount" id="mpCouponApplyed"> Coupon ok </span>
                                <span class="mp-error" id="mpCouponError">
                                    <?php echo $helper->__('The code you entered is incorrect'); ?>
                                </span>
                            </div>
                        </div>
                    </div>

                    <!--                    Card Details-->
                    <div class="mp-row-checkout">
                        <div class="mp-col-md-12">
                            <div class="mp-frame-tarjetas">
                                <p class="mp-subtitle-custom-checkout">
                                    <?php echo $helper->__('Enter your card details'); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <!--                    New Card-->

                    <div id="mercadopago-form">
                        <!--                            New Card-->
                        <div class="mp-row-checkout mp-pt-10">
                            <div class="mp-col-md-12">
                                <label for="mpCardNumber"
                                       class="mp-label-form"><?php echo $helper->__('Card number'); ?>
                                    <em>*</em></label>
                                <input type="text" class="mp-form-control mp-mt-5 required-entry"
                                       onkeypress="maskDate(this, mcc)"
                                       id="mpCardNumber" data-checkout="mpCardNumber"
                                       title="<?php echo $helper->__('Card number'); ?>"
                                       placeholder="XXXX XXXX XXXX XXXX"
                                       autocomplete="off" maxlength="24"/>

                                <span class="mp-error mp-mt-5" id="mp-error-205"
                                      data-main="#mpCardNumber"><?php echo $helper->__('Card number'); ?></span>
                                <span class="mp-error mp-mt-5" id="mp-error-E301"
                                      data-main="#mpCardNumber"><?php echo $helper->__('Invalid Card Number'); ?></span>
                            </div>
                        </div>
                        <!--                            Name and Surname-->
                        <div class="mp-row-checkout mp-pt-10">
                            <div class="mp-col-md-12">
                                <label for="cardholderName"
                                       class="mp-label-form">
                                    <?php echo $helper->__('Name and surname of the cardholder'); ?>
                                    <em>*</em></label>
                                <input type="text" class="mp-form-control mp-mt-5" id="mpCardholderName"
                                       name="mercadopago_custom[cardholderName]" placeholder="Nombre y Apellido"
                                       data-checkout="mpCardholderName" autocomplete="off"/>
                                <span class="mp-error mp-mt-5" id="mp-error-221"
                                      data-main="#mpCardholderName"><?php echo $helper->__('Card number'); ?></span>
                                <span class="mp-error mp-mt-5" id="mp-error-316"
                                      data-main="#mpCardholderName"><?php echo $helper->__('Invalid cardholder name'); ?></span>
                            </div>
                        </div>
                        <!--                            Expiration Date and CVV-->
                        <div class="mp-row-checkout mp-pt-10">
                            <div class="mp-col-md-6 mp-pr-15">
                                <label for="mpCardExpirationDate"
                                       class="mp-label-form"><?php echo $helper->__('Expiration date'); ?>
                                    <em>*</em></label>
                                <input type="text" class="mp-form-control mp-mt-5" id="mpCardExpirationDate"
                                       data-checkout="mpCardExpirationDate"
                                       name="mercadopago_custom[cardExpirationDate]"
                                       onkeypress="maskDate(this, mdate)"
                                       autocomplete="off" placeholder="MM/AAAA" maxlength="7"/>
                                <input type="hidden" id="mpCardExpirationMonth"
                                       name="mercadopago_custom[cardExpirationMonth]"
                                       data-checkout="mpCardExpirationMonth">
                                <input type="hidden" id="mpCardExpirationYear"
                                       name="mercadopago_custom[cardExpirationYear]"
                                       data-checkout="mpCardExpirationYear">
                                <span class="mp-error mp-mt-5" id="mp-error-208"
                                      data-main="#mpCardExpirationDate"><?php echo $helper->__('Invalid Expiration Date'); ?></span>
                            </div>

                            <div class="mp-col-md-6">
                                <label for="mpSecurityCode"
                                       class="mp-label-form"><?php echo $helper->__('Last 3 numbers on the back'); ?>
                                    <em>*</em></label>
                                <input type="text" class="mp-form-control mp-mt-5"
                                       id="mpSecurityCode" data-checkout="mpSecurityCode" autocomplete="off"
                                       maxlength="4" onkeypress="maskDate(this, minteger)"
                                       placeholder="CVV"/>
                                <p class="mp-desc mp-mt-5 mp-mb-0"
                                   data-main="#mpSecurityCode"><?php echo $helper->__('Last 3 numbers on the back'); ?></p>
                                <span class="mp-error mp-mt-5" id="mp-error-224"
                                      data-main="#mpSecurityCode"><<?php echo $helper->__('Card number'); ?></span>
                                <span class="mp-error mp-mt-5" id="mp-error-E302"
                                      data-main="#mpSecurityCode"><?php echo $helper->__('Invalid Card Number'); ?></span>
                            </div>
                        </div>
                        <!--                            Issuer And Installments-->
                        <div class="mp-row-checkout">
                            <div class="mp-col-md-12">
                                <div class="mp-frame-tarjetas">
                                    <p class="mp-subtitle-custom-checkout">
                                        <?php echo $helper->__('In how many installments do you want to pay?') ?>
                                    </p>

                                    <div class="mp-row-checkout mp-pt-10">
                                        <div class="mp-col-md-6 mp-pr-15">
                                            <div class="mp-issuer">
                                                <label for="mp-checkout-issuer" class="mp-label-form">
                                                    <?php echo $helper->__('Issuer'); ?><em>*</em>
                                                </label>
                                                <select class="mp-form-control mp-pointer" id="mp-checkout-issuer"
                                                        data-checkout="mp-checkout-issuer"
                                                        name="mercadopago_custom[issuer]"></select>
                                            </div>
                                        </div>

                                        <div id="mp-installments-div" class="mp-col-md-6 mp-installment">
                                            <?php if ($currency_ratio != 1) : ?>
                                                <label for="installments" class="mp-label-form">
                                                    <div class="mp-tooltip">
                                                        <?php echo $helper->__(''); ?>
                                                        <span class="mp-tooltiptext">
                                                            <?php echo $helper->__('Converted payment of') . " " . $woocommerce_currency . " " . $helper->__('for') . " " . $account_currency; ?>
                                                        </span>
                                                    </div>
                                                    <em>*</em>
                                                </label>
                                            <?php else : ?>
                                                <label for="mp-checkout-installments" class="mp-label-form">
                                                    <?php echo $helper->__('Select the number of installment'); ?>
                                                </label>
                                            <?php endif; ?>
                                            <select class="mp-form-control mp-pointer mp-mt-5"
                                                    id="mp-checkout-installments"
                                                    data-checkout="mp-checkout-installments"
                                                    name="mercadopago_custom[installments]"></select>
                                            <div id="mp-box-input-tax-cft">
                                                <div id="mp-box-input-tax-tea">
                                                    <div id="mp-tax-tea-text"></div>
                                                </div>
                                                <div id="mp-tax-cft-text"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--                            Document-->
                        <div class="mp-row-checkout">
                            <div id="mp-doc-div" class="mp-col-md-12 mp-doc mp-docType">
                                <div class="mp-frame-tarjetas">
                                    <p class="mp-subtitle-custom-checkout">
                                        <?php echo $helper->__('Enter your document number') ?>
                                    </p>
                                    <div class="mp-row-checkout mp-pt-10">
                                        <div class="mp-col-md-2 mp-pr-15 mp-pt-5">
                                            <label for="mpDocType" class="mp-label-form">
                                                <?php echo $helper->__('Type'); ?>
                                            </label>
                                            <select id="mpDocType" class="mp-form-control mp-pointer mp-mt-5"
                                                    data-checkout="mpDocType"
                                                    name="mercadopago_custom[docType]"></select>

                                            <span class="mp-error" id="mp-error-212" data-main="#mpDocType"> <?php echo $helper->__('Parameter docType can not be null/empty'); ?> </span>
                                            <span class="mp-error" id="mp-error-322" data-main="#mpDocType"> <?php echo $helper->__('Invalid Document Type'); ?> </span>
                                        </div>

                                        <div class="mp-col-md-4 mp-pr-15 mp-pt-5">
                                            <label for="mpDocNumber"
                                                   class="mp-label-form"><?php echo $helper->__('Document number'); ?>
                                                <em>*</em></label>
                                            <input type="text" class="mp-form-control mp-mt-5" id="mpDocNumber"
                                                   data-checkout="mpDocNumber" name="mercadopago_custom[docNumber]"
                                                   autocomplete="off"/>
                                            <p class="mp-desc mp-mt-5 mp-mb-0"
                                               data-main="#mpSecurityCode"><?php echo $helper->__('Only numbers'); ?></p>
                                            <span class="mp-error mp-mt-5" id="mp-error-214" data-main="#mpDocNumber">
                                                <?php echo $helper->__('Card number'); ?>
                                            </span>
                                            <span class="mp-error mp-mt-5" id="mp-error-324" data-main="#mpDocNumber">
                                                <?php echo $helper->__('Invalid Document Number'); ?>
                                            </span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!--                            Save Card-->
                        <div class="mp-row-checkout">
                            <div class="mp-col-md-12 mp-pt-10">
                                <div class="mp-frame-tarjetas">
                                    <div class="mp-row-checkout mp-pt-10">
                                        <label for="doNotSaveCard" class="mp-label-form-check mp-pointer"
                                               style="display: inline;">
                                            <input class="mp-form-control-check" type="checkbox"
                                                   name="mercadopago_custom[doNotSaveCard]" id="doNotSaveCard"
                                                   value="yes">
                                            <?php echo $helper->__('Do not save card'); ?>
                                        </label>
                                        <p class="mp-obrigatory">
                                            <em>*</em> <b><?php echo $helper->__('Obligatory field'); ?></b>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- NOT DELETE LOADING-->
                    <div id="mp-box-loading"></div>

                    <div class="mp-row-checkout">
                        <div class="mp-col-md-12">
                            <div class="mp-col-md-6">
                                <label class="mp-checkout-proccess-text">
                                    Processado por Mercado Pago
                                </label>
                                <img src="<?php echo $this->getSkinUrl('mercadopago/images/logo.png'); ?>"
                                     class="mp-checkout-logo-terms">
                            </div>
                            <div class="mp-col-md-6">
                                <label class="mp-checkout-terms">
                                    Al pagar, afirmo que soy mayor de edad y acepto los Términos y condiciones de
                                    Mercado Pago
                                </label>
                            </div>
                        </div>
                    </div>

                </div>
            </div>


            <div class="mp-box-inputs mp-col-100" id="mercadopago-utilities">
                <p><b>Debug Mode <span class="flag-on">ON</span></b></p>
                site_id <input type="text" id="mp_site_id" name="payment[<?php echo $_code; ?>][site_id]"/> <br/>
                amount: <input type="text" id="mp_amount" value="<?php echo $grant_total; ?>" name="payment[<?php echo $_code; ?>][amount]"/> <br/>
                total amount: <input type="text" id="mp_total_amount" name="payment[<?php echo $_code; ?>][total_amount]"/> <br/>
                paymentMethodId <input type="text" id="mp_paymentMethodId" name="payment[<?php echo $_code; ?>][paymentMethodId]"/> <br/>
                token <input type="text" id="mp_token" name="payment[<?php echo $_code; ?>][token]"/> <br/>
                cardTruncated <input type="text" id="mp_cardTruncated" name="payment[<?php echo $_code; ?>][cardTruncated]"/> <br/>
                CustomerAndCard <input type="text" id="mp_customerAndCard" name="payment[<?php echo $_code; ?>][CustomerAndCard]"/> <br/>
                mercadopago-gateway-mode <input type="text" id="mp-mercadopago-gateway-mode" name="payment[<?php echo $_code; ?>][gateway_mode]"/> <br/>
                customer_id <input type="text" name="payment[<?php echo $_code; ?>][customer_id]" value="<?php echo $customer['id']; ?>"> <br/>
                campaign_id <input type="text" id="mp_campaign_id" name="payment[<?php echo $_code; ?>][campaign_id]"/><br/>
                campaign <input type="text" id="mp_campaign" name="payment[<?php echo $_code; ?>][campaign]"/> <br/>
                discount <input type="text" id="mp_discount" name="payment[<?php echo $_code; ?>][discount]"/> <br/>
            </div>
        </div>


    </li>
</ul>


<script>


    var mercadopago_site_id = '<?php echo strtoupper($country); ?>';
    var mercadopago_public_key = '<?php echo $public_key; ?>';
    var mercadopago_payer_email = '<?php echo $payer_email; ?>';
    var mercadopago_url_coupon = '<?php echo $base_url; ?>mercadopago/api/coupon';
    var mercadopago_url_amount = '<?php echo $base_url; ?>mercadopago/api/amount';

    //initialize loading
    MPv1.paths.loading = '<?php echo $this->getSkinUrl('mercadopago/images/loading.gif'); ?>';
    MPv1.paths.check = '<?php echo $this->getSkinUrl('mercadopago/images/check.png'); ?>';
    MPv1.paths.error = '<?php echo $this->getSkinUrl('mercadopago/images/error.png'); ?>';

    //add text translations
    MPv1.text.choose = '<?php echo $form_labels["form"]["label_choose"]; ?>';
    MPv1.text.other_bank = '<?php echo $form_labels["form"]["label_other_bank"]; ?>';
    MPv1.text.discount_info1 = '<?php echo $form_labels["form"]["discount_info1"]; ?>';
    MPv1.text.discount_info2 = '<?php echo $form_labels["form"]["discount_info2"]; ?>';
    MPv1.text.discount_info3 = '<?php echo $form_labels["form"]["discount_info3"]; ?>';
    MPv1.text.discount_info4 = '<?php echo $form_labels["form"]["discount_info4"]; ?>';
    MPv1.text.discount_info5 = '<?php echo $form_labels["form"]["discount_info5"]; ?>';
    MPv1.text.discount_info6 = '<?php echo $form_labels["form"]["discount_info6"]; ?>';
    MPv1.text.apply = '<?php echo $form_labels["form"]["apply"]; ?>';
    MPv1.text.remove = '<?php echo $form_labels["form"]["remove"]; ?>';
    MPv1.text.coupon_empty = '<?php echo $form_labels["form"]["coupon_empty"]; ?>';
    MPv1.debug = <?php echo $debugMode; ?>;
    MPv1.gateway_mode = <?php echo $modeGateway; ?>;

    MPv1.Initialize(mercadopago_site_id, mercadopago_public_key, <?php echo $coupon_mercadopago; ?>, mercadopago_url_coupon, mercadopago_payer_email);


    MPv1.AJAX({
        url: mercadopago_url_amount,
        method: "GET",
        timeout: 5000,
        error: function () {
            console.log("Fail get amount");
        },
        success: function (status, response) {
            document.querySelector(MPv1.selectors.amount).value = response.amount;
        }
    });


    /***************************************
     *
     *
     * For OSC
     *
     */

    //force update amount in form
    document.querySelector(MPv1.selectors.amount).value = '<?php echo $grant_total; ?>';

    //check exist value card in input
    var cc = document.querySelector(MPv1.selectors.cardNumber);
    if (cc.value != "") {
        //force guessingPaymentMethod
        MPv1.guessingPaymentMethod({type: 'keyup'});
    }

    if (typeof OnestepcheckoutForm === 'function') {
        OnestepcheckoutForm.prototype.placeOrder = function () {
            var token = document.querySelector(MPv1.selectors.token);

            if (token.value == "" && document.querySelector('input[name="payment[method]"]:checked').value == 'mercadopago_custom') {
                MPv1.hideErrors();
                document.querySelector(MPv1.selectors.box_loading).style.background = "url(" + MPv1.paths.loading + ") 0 50% no-repeat #fff";
                var $form = MPv1.getForm();
                Mercadopago.createToken($form, MPv1.sdkResponseHandlerCustom);
                return false;
            }

            if (this.validate()) {
                this.showOverlay();
                this.showPleaseWaitNotice();
                this.disablePlaceOrderButton();
                new Ajax.Request(this.placeOrderUrl, {
                    method: 'post',
                    parameters: Form.serialize(this.form.form, true),
                    onComplete: this.onComplete.bindAsEventListener(this)
                })
            }
        }
        MPv1.sdkResponseHandlerCustom = function (status, response) {
            var $form = MPv1.getForm();
            document.querySelector(MPv1.selectors.box_loading).style.background = "";
            if (status != 200 && status != 201) {
                MPv1.showErrors(response);
            } else {
                var token = document.querySelector(MPv1.selectors.token);
                token.value = response.id;
                //get button OSC BRASIL
                var btnPlaceOrder = document.querySelector("#onestepcheckout-place-order-button")
                btnPlaceOrder.click();
            }
        }
    }

</script>
