<?php
$grant_total = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
$coupon_mercadopago = Mage::getStoreConfig('payment/mercadopago_custom/coupon_mercadopago') == 1 ? 'true' : 'false';
$country = Mage::getStoreConfig('payment/mercadopago/country');
$_code = $this->getMethodCode();
$debugMode = Mage::getStoreConfigFlag('payment/mercadopago/debug_mode') == 1 ? 'true' : 'false';

$customer = $this->getCustomerAndCards();
$public_key = Mage::getStoreConfig(MercadoPago_Core_Helper_Data::XML_PATH_PUBLIC_KEY);

//@Gateway_Mode
$modeGateway = Mage::getStoreConfigFlag('payment/mercadopago_custom/enable_gateway') == 1 ? 'true' : 'false';

$customer_session = Mage::getSingleton('customer/session')->getCustomer();
$payer_email = $customer_session->getEmail();

// $route = $this->getRequest()->getRequestedRouteName();
$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true);
?>
<script type="text/javascript">
    if (typeof sendAnalyticsData === 'function') {
        sendAnalyticsData("<?php echo $_code ?>");
    }
</script>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mercadopago/css/mp_checkout_custom.css'); ?>" />

<ul class="form-list form-mercadopago" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li class="card-form first-card">
        <div id="mp_checkout_object_fit">
<!--            <div class="mp_checkout_center">-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <div class="mp_checkout_informations">-->
<!--                        <div class="mp_checkout_installmentswarning">Hasta XX cuotas</div>-->
<!--                        <span class="mp_checkout_arrow_down"> Con qué Tarjetas puedo pagar</span>-->
<!--                        <span> Ver promociones vigentes</span>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <div class="mp_checkout_title1">Ingresa tu cupón de descuento</div>-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <input type="text" class="mp_checkout_input" placeholder="0000 0000 0000 0000">-->
<!--                    <input type="button" class="mp_checkout_button_apply" value="Aplicar">-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <div class="mp_checkout_title1">Ingresa los datos de tu tarjeta</div>-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <div class="mp_checkout_label">Número de Tarjeta <p>*</p></div>-->
<!--                    <input type="text" class="mp_checkout_input" placeholder="0000 0000 0000 0000">-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <div class="mp_checkout_label">Nombre y apellido del titular de la tarjeta <p>*</p></div>-->
<!--                    <input type="text" class="mp_checkout_input" placeholder="Nombre y apelido">-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_row">-->
<!--                    <div class="mp_checkout_half_row">-->
<!--                        <div class="mp_checkout_label">Fecha de vencimiento <p>*</p></div>-->
<!--                        <input type="text" class="mp_checkout_input" placeholder="MM / AAAA">-->
<!--                    </div>-->
<!--                    <div class="mp_checkout_half_row mp_checkout_margin_left_30">-->
<!--                        <div class="mp_checkout_label" Código de seguridad-->
<!--                        <p>*</p></div>-->
<!--                    <input type="text" class="mp_checkout_input" placeholder="CVV">-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            <div class="mp_checkout_row">-->
<!--                <div class="mp_checkout_title1">Ingresa los datos de tu tarjeta</div>-->
<!--            </div>-->
<!---->
<!--            <div class="mp_checkout_row">-->
<!--                <div class="mp_checkout_half_row">-->
<!--                    <label for="User">Banco Emissor *</label>-->
<!--                    <select>-->
<!--                        <option>teste</option>-->
<!--                    </select>-->
<!--                </div>-->
<!---->
<!--                <div class="mp_checkout_half_row">-->
<!--                    <select>-->
<!--                        <option>1 cuota</option>-->
<!--                    </select>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            <div class="mp_checkout_row">-->
<!--                <div class="mp_checkout_title1">Ingresá tu número de documento</div>-->
<!--            </div>-->
<!---->
<!--            <div class="mp_checkout_row">-->
<!--                <div class="mp_checkout_half_row">-->
<!--                    <label for="mp_checkout_type">Tipo</label>-->
<!--                    <select id="mp_checkout_type">-->
<!--                        <option>DNI</option>-->
<!--                    </select>-->
<!---->
<!--                    <label for="mp_checkout_doc">Numero do documento</label>-->
<!--                    <input type="text" id="mp_checkout_doc">-->
<!---->
<!--                </div>-->
<!--            </div>-->
<!---->
<!---->
<!--        </div>-->

        <?php
        $credit_card = array();
        $debit_card = array();
        $customer_cards = array();
        $currency_ratio =1;
        $woocommerce_currency = 2;
        $account_currency = 3;
        $amount = 200;
        $customerId = 32;

        function esc_html__($a, $b){
            return __($a, $b);
        }
        ?>

        <div class="panel-custom-checkout">
            <div class="row">
                <div class="mp-frame-links">
                    <a class="mp-checkout-link pr-10" id="button-show-payments">
                        <?= __('Con qué Tarjetas puedo pagar', 'woocommerce-mercadopago') ?> ⌵
                    </a>
                    <span id="mp_promotion_link"> | </span>
                    <a href="https://www.mercadopago.com.ar/cuotas" id="mp_checkout_link" class="mp-checkout-link pl-10" target="_blank">
                        <?= __('Ver promociones vigentes', 'woocommerce-mercadopago') ?>
                    </a>
                </div>

                <div class="col-md-12" id="mercadopago-form-coupon">
                    <div class="frame-tarjetas text-justify">
                        <p class="subtitle-custom-checkout"><?= __('Ingresa tu cupón de descuento', 'woocommerce-mercadopago') ?></p>

                        <div class="row pt-10">
                            <div class="col-md-9 pr-15">
                                <input type="text" class="mp-form-control" id="couponCode" name="mercadopago_custom[coupon_code]" autocomplete="off" maxlength="24" placeholder="<?= __('Ingresa tu cupón', 'woocommerce-mercadopago') ?>" />
                            </div>

                            <div class="col-md-3">
                                <input type="button" class="mp-button pointer" id="applyCoupon" value="aplicar">
                            </div>
                        </div>

                        <span class="mp-discount" id="mpCouponApplyed"></span>
                        <span class="mp-error" id="mpCouponError"><?= __('El código que ingresaste es incorrecto', 'woocommerce-mercadopago') ?></span>
                    </div>
                </div>

                <div class="frame-payments" id="frame-payments">
                    <div class="col-md-12">
                        <div class="frame-tarjetas">
                            <?php if (count($credit_card) != 0) : ?>
                                <p class="subtitle-checkout-custom"><?= __('Tarjetas de crédito', 'woocommerce-mercadopago') ?></p>
                                <?php foreach ($credit_card as $credit_image) : ?>
                                    <img src="<?= $credit_image ?>" class="img-fluid img-tarjetas" alt="" />
                                <?php endforeach; ?>
                            <?php endif; ?>

                            <?php if (count($debit_card) != 0) : ?>
                                <p class="subtitle-checkout-custom pt-10"><?= __('Tarjetas de débito', 'woocommerce-mercadopago') ?></p>
                                <?php foreach ($debit_card as $debit_image) : ?>
                                    <img src="<?= $debit_image ?>" class="img-fluid img-tarjetas" alt="" />
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>



                <div class="col-md-12">
                    <div class="frame-tarjetas">
                        <p class="subtitle-custom-checkout"><?= __('Ingresa los datos de tu tarjeta', 'woocommerce-mercadopago') ?></p>

                        <!-- saved cards -->
                        <div id="mercadopago-form-customer-and-card">
                            <div class="row pt-10">
                                <div class="col-md-12">
                                    <label for="paymentMethodIdSelector" class="mp-label-form">Payment Method <em>*</em></label>
                                    <select id="paymentMethodSelector" class="mp-form-control pointer" name="mercadopago_custom[paymentMethodSelector]" data-checkout="cardId">
                                        <optgroup label="Tu tarjeta" id="payment-methods-for-customer-and-cards">
                                            <?php foreach ($customer_cards as $card) : ?>
                                                <option value="<?= $card['id']; ?>
															first_six_digits=<?= $card['first_six_digits']; ?>
															last_four_digits=<?= $card['last_four_digits']; ?>
															security_code_length=<?= $card['security_code']['length']; ?>
															type_checkout='customer_and_card'
															payment_method_id=<?= $card['payment_method']['id']; ?>">
                                                    <?= ucfirst($card['payment_method']['name']); ?>
                                                    <?= __('terminó en', 'woocommerce-mercadopago'); ?>
                                                    <?= $card['last_four_digits']; ?>
                                                </option>
                                            <?php endforeach; ?>
                                        </optgroup>

                                        <optgroup label="<?= __('Otras tarjetas', 'woocommerce-mercadopago'); ?>" id="payment-methods-list-other-cards">
                                            <option value="-1"><?= __('Otra tarjeta', 'woocommerce-mercadopago'); ?></option>
                                        </optgroup>
                                    </select>
                                </div>

                                <div class="col-md-4">
                                    <div id="mp-securityCode-customer-and-card">
                                        <div class="mp-box-inputs mp-col-45">
                                            <label for="customer-and-card-securityCode" class="mp-label-form"><?= __('CVV', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                            <input type="text" onkeyup="maskDate(this, minteger);" class="mp-form-control" id="customer-and-card-securityCode" data-checkout="securityCode" autocomplete="off" maxlength="4" />

                                            <span class="mp-error" id="mp-error-224" data-main="#customer-and-card-securityCode"><?= __('Este campo no puede estar vacío', 'woocommerce-mercadopago'); ?></span>
                                            <span class="mp-error" id="mp-error-E302" data-main="#customer-and-card-securityCode"><?= __('Código de seguridad invalido', 'woocommerce-mercadopago'); ?></span>
                                            <span class="mp-error" id="mp-error-E203" data-main="#customer-and-card-securityCode"><?= __('Código de seguridad invalido', 'woocommerce-mercadopago'); ?></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end saved cards -->

                        <!-- new card -->
                        <div id="mercadopago-form">
                            <div class="row pt-10">
                                <div class="col-md-12">
                                    <label for="cardNumber" class="mp-label-form"><?= esc_html__('Número de Tarjeta', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                    <input type="text" onkeyup="maskDate(this, mcc);" class="mp-form-control mt-5" id="cardNumber" data-checkout="cardNumber" autocomplete="off" maxlength="23" />

                                    <span class="mp-error mt-5" id="mp-error-205" data-main="#cardNumber"><?= esc_html__('Este campo no puede estar vacío', 'woocommerce-mercadopago'); ?></span>
                                    <span class="mp-error mt-5" id="mp-error-E301" data-main="#cardNumber"><?= esc_html__('Numero de tarjeta invalido', 'woocommerce-mercadopago'); ?></span>
                                </div>
                            </div>

                            <div class="row pt-10">
                                <div class="col-md-12">
                                    <label for="cardholderName" class="mp-label-form"><?= esc_html__('Nombre y apellido del titular de la tarjeta', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                    <input type="text" class="mp-form-control mt-5" id="cardholderName" name="mercadopago_custom[cardholderName]" data-checkout="cardholderName" autocomplete="off" />

                                    <span class="mp-error mt-5" id="mp-error-221" data-main="#cardholderName"><?= esc_html__('Este campo no puede estar vacío', 'woocommerce-mercadopago'); ?></span>
                                    <span class="mp-error mt-5" id="mp-error-316" data-main="#cardholderName"><?= esc_html__('Nombre del titular de la tarjeta no válido', 'woocommerce-mercadopago'); ?></span>
                                </div>
                            </div>

                            <div class="row pt-10">
                                <div class="col-md-6 pr-15">
                                    <label for="cardholderName" class="mp-label-form"><?= esc_html__('Fecha de vencimiento', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                    <input type="text" onkeyup="maskDate(this, mdate);" onblur="validateMonthYear()" class="mp-form-control mt-5" id="cardExpirationDate" data-checkout="cardExpirationDate" name="mercadopago_custom[cardExpirationDate]" autocomplete="off" placeholder="MM/AAAA" maxlength="7" />
                                    <input type="hidden" id="cardExpirationMonth" name="mercadopago_custom[cardExpirationMonth]" data-checkout="cardExpirationMonth">
                                    <input type="hidden" id="cardExpirationYear" name="mercadopago_custom[cardExpirationYear]" data-checkout="cardExpirationYear">

                                    <span class="mp-error mt-5" id="mp-error-208" data-main="#cardExpirationDate"><?= esc_html__('Fecha de expiracion inválida', 'woocommerce-mercadopago'); ?></span>
                                </div>

                                <div class="col-md-6">
                                    <label for="securityCode" class="mp-label-form"><?= esc_html__('Código de seguridad', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                    <input type="text" onkeyup="maskDate(this, minteger);" class="mp-form-control mt-5" id="securityCode" data-checkout="securityCode" autocomplete="off" maxlength="4" />

                                    <p class="mp-desc mt-5 mb-0" data-main="#securityCode"><?= esc_html__('Últimos 3 números del dorso', 'woocommerce-mercadopago'); ?></p>
                                    <span class="mp-error mt-5" id="mp-error-224" data-main="#securityCode"><?= esc_html__('Este campo no puede estar vacío', 'woocommerce-mercadopago'); ?></span>
                                    <span class="mp-error mt-5" id="mp-error-E302" data-main="#securityCode"><?= esc_html__('Código de seguridad invalido', 'woocommerce-mercadopago'); ?></span>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="frame-tarjetas">
                                    <p class="subtitle-custom-checkout"><?= __('En cuántas cuotas quieres pagar', 'woocommerce-mercadopago') ?></p>

                                    <div class="row pt-10">
                                        <div class="col-md-4 pr-15">
                                            <div class="mp-issuer">
                                                <label for="issuer" class="mp-label-form"><?= esc_html__('Issuer', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                                <select class="mp-form-control pointer mt-5" id="issuer" data-checkout="issuer" name="mercadopago_custom[issuer]"></select>
                                            </div>
                                        </div>

                                        <div id="installments-div" class="col-md-8">
                                            <?php

                                            if ($currency_ratio != 1) : ?>
                                                <label for="installments" class="mp-label-form">
                                                    <div class="tooltip">
                                                        <?= esc_html__('', 'woocommerce-mercadopago'); ?>
                                                        <span class="tooltiptext">
												<?=
                                                esc_html__('Pago convertido de', 'woocommerce-mercadopago') . " " .
                                                $woocommerce_currency . " " . esc_html__('para', 'woocommerce-mercadopago') . " " .
                                                $account_currency;
                                                ?>
											</span>
                                                    </div>
                                                    <em>*</em>
                                                </label>
                                            <?php else : ?>
                                                <label for="installments" class="mp-label-form"><?= __('Seleccione el número de cotas', 'woocommerce-mercadopago') ?></label>
                                            <?php endif; ?>

                                            <select class="mp-form-control pointer mt-5" id="installments" data-checkout="installments" name="mercadopago_custom[installments]"></select>

                                            <div id="mp-box-input-tax-cft">
                                                <div id="mp-box-input-tax-tea">
                                                    <div id="mp-tax-tea-text"></div>
                                                </div>
                                                <div id="mp-tax-cft-text"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="mp-doc-div" class="col-md-12 mp-doc">
                                <div class="frame-tarjetas">
                                    <p class="subtitle-custom-checkout"><?= __('Ingresa tu número de documento', 'woocommerce-mercadopago') ?></p>

                                    <div class="row pt-10">
                                        <div class="col-md-4 pr-15">
                                            <label for="docType" class="mp-label-form"><?= esc_html__('Tipo', 'woocommerce-mercadopago'); ?></label>
                                            <select id="docType" class="mp-form-control pointer mt-5" data-checkout="docType" name="mercadopago_custom[docType]"></select>
                                        </div>

                                        <div class="col-md-8">
                                            <label for="docNumber" class="mp-label-form"><?= esc_html__('Número de documento', 'woocommerce-mercadopago'); ?> <em>*</em></label>
                                            <input type="text" class="mp-form-control mt-5" id="docNumber" data-checkout="docNumber" name="mercadopago_custom[docNumber]" autocomplete="off" />
                                            <p class="mp-desc mt-5 mb-0" data-main="#securityCode"><?= esc_html__('Sólo números', 'woocommerce-mercadopago'); ?></p>

                                            <span class="mp-error mt-5" id="mp-error-214" data-main="#docNumber"><?= esc_html__('Este campo no puede estar vacío', 'woocommerce-mercadopago'); ?></span>
                                            <span class="mp-error mt-5" id="mp-error-324" data-main="#docNumber"><?= esc_html__('Número de documento no válido', 'woocommerce-mercadopago'); ?></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-12 pt-10">
                                <div class="frame-tarjetas">
                                    <div class="row pt-10">
                                        <label for="doNotSaveCard" class="mp-label-form-check pointer" style="display: inline;">
                                            <input class="mp-form-control-check" type="checkbox" name="mercadopago_custom[doNotSaveCard]" id="doNotSaveCard" value="yes">
                                            <?= esc_html__('No guardar la tarjeta', 'woocommerce-mercadopago'); ?>
                                        </label>
                                        <p class="mp-obrigatory"><em>*</em> <?= esc_html__('Campo obligatorio', 'woocommerce-mercadopago'); ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end new card -->

                        <!-- NOT DELETE LOADING-->
                        <div id="mp-box-loading"></div>

                    </div>
                </div>

                <div id="mercadopago-utilities">
                    <input type="hidden" id="site_id" name="mercadopago_custom[site_id]" />
                    <input type="hidden" id="amount" value='<?php echo $amount; ?>' name="mercadopago_custom[amount]" />
                    <input type="hidden" id="currency_ratio" value='<?php echo $currency_ratio; ?>' name="mercadopago_custom[currency_ratio]" />
                    <input type="hidden" id="campaign_id" name="mercadopago_custom[campaign_id]" />
                    <input type="hidden" id="campaign" name="mercadopago_custom[campaign]" />
                    <input type="hidden" id="discount" name="mercadopago_custom[discount]" />
                    <input type="hidden" id="paymentMethodId" name="mercadopago_custom[paymentMethodId]" />
                    <input type="hidden" id="token" name="mercadopago_custom[token]" />
                    <input type="hidden" id="cardTruncated" name="mercadopago_custom[cardTruncated]" />
                    <input type="hidden" id="CustomerAndCard" name="mercadopago_custom[CustomerAndCard]" />
                    <input type="hidden" id="CustomerId" value='<?php echo $customerId; ?>' name="mercadopago_custom[CustomerId]" />
                </div>

            </div>
        </div>


</div>

    </li>
</ul>


<script>
    var mercadopago_site_id = '<?php echo strtoupper($country); ?>';
    var mercadopago_public_key = '<?php echo $public_key; ?>';
    var mercadopago_payer_email = '<?php echo $payer_email; ?>';
    var mercadopago_url_coupon = '<?php echo $base_url; ?>mercadopago/api/coupon';
    var mercadopago_url_amount = '<?php echo $base_url; ?>mercadopago/api/amount';

    //initialize loading
    MPv1.paths.loading = '<?php echo $this->getSkinUrl('mercadopago/images/loading.gif'); ?>';
    MPv1.paths.check = '<?php echo $this->getSkinUrl('mercadopago/images/check.png'); ?>';
    MPv1.paths.error = '<?php echo $this->getSkinUrl('mercadopago/images/error.png'); ?>';

    //add text translations
    MPv1.text.choose = '<?php echo $form_labels["form"]["label_choose"]; ?>';
    MPv1.text.other_bank = '<?php echo $form_labels["form"]["label_other_bank"]; ?>';
    MPv1.text.discount_info1 = '<?php echo $form_labels["form"]["discount_info1"]; ?>';
    MPv1.text.discount_info2 = '<?php echo $form_labels["form"]["discount_info2"]; ?>';
    MPv1.text.discount_info3 = '<?php echo $form_labels["form"]["discount_info3"]; ?>';
    MPv1.text.discount_info4 = '<?php echo $form_labels["form"]["discount_info4"]; ?>';
    MPv1.text.discount_info5 = '<?php echo $form_labels["form"]["discount_info5"]; ?>';
    MPv1.text.discount_info6 = '<?php echo $form_labels["form"]["discount_info6"]; ?>';
    MPv1.text.apply = '<?php echo $form_labels["form"]["apply"]; ?>';
    MPv1.text.remove = '<?php echo $form_labels["form"]["remove"]; ?>';
    MPv1.text.coupon_empty = '<?php echo $form_labels["form"]["coupon_empty"]; ?>';

    MPv1.debug = <?php echo $debugMode; ?>;
    MPv1.gateway_mode = <?php echo $modeGateway; ?>;

    MPv1.Initialize(mercadopago_site_id, mercadopago_public_key, <?php echo $coupon_mercadopago; ?>, mercadopago_url_coupon, mercadopago_payer_email);


    /***************************************
     *
     *
     * Customizações
     *
     */

    MPv1.AJAX({
        url: mercadopago_url_amount,
        method: "GET",
        timeout: 5000,
        error: function () {
            // request failed
            console.log("Fail get amount");
        },
        success: function (status, response) {
            document.querySelector(MPv1.selectors.amount).value = response.amount;
        }
    });


    /***************************************
     *
     *
     * For OSC
     *
     */

    //force update amount in form
    document.querySelector(MPv1.selectors.amount).value = '<?php echo $grant_total; ?>';

    //check exist value card in input
    var cc = document.querySelector(MPv1.selectors.cardNumber);
    if (cc.value != "") {
        //force guessingPaymentMethod
        MPv1.guessingPaymentMethod({type: 'keyup'});
    }

    if (typeof OnestepcheckoutForm === 'function') {
        OnestepcheckoutForm.prototype.placeOrder = function () {
            var token = document.querySelector(MPv1.selectors.token);

            if (token.value == "" && document.querySelector('input[name="payment[method]"]:checked').value == 'mercadopago_custom') {
                MPv1.hideErrors();
                document.querySelector(MPv1.selectors.box_loading).style.background = "url(" + MPv1.paths.loading + ") 0 50% no-repeat #fff";
                var $form = MPv1.getForm();
                Mercadopago.createToken($form, MPv1.sdkResponseHandlerCustom);
                return false;
            }

            if (this.validate()) {
                this.showOverlay();
                this.showPleaseWaitNotice();
                this.disablePlaceOrderButton();
                new Ajax.Request(this.placeOrderUrl, {
                    method: 'post',
                    parameters: Form.serialize(this.form.form, true),
                    onComplete: this.onComplete.bindAsEventListener(this)
                })
            }
        }
        MPv1.sdkResponseHandlerCustom = function (status, response) {
            var $form = MPv1.getForm();
            document.querySelector(MPv1.selectors.box_loading).style.background = "";
            if (status != 200 && status != 201) {
                MPv1.showErrors(response);
            } else {
                var token = document.querySelector(MPv1.selectors.token);
                token.value = response.id;
                //get button OSC BRASIL
                var btnPlaceOrder = document.querySelector("#onestepcheckout-place-order-button")
                btnPlaceOrder.click();
            }
        }
    }

</script>


<?php if ($this->getMethod()->getConfigData('communication') != ""): ?>
    <p class="communication"><?php echo $this->getMethod()->getConfigData('communication') ?></p>
<?php endif; ?>
<?php if ($this->getMethod()->getConfigData('banner_checkout') != ""): ?>
    <img src="<?php echo $this->getMethod()->getConfigData('banner_checkout'); ?>" class="banner_checkout_mp"/>
<?php endif; ?>
