<tr>
    <td colspan="10">
        <div class="margin-top-30">
                <span class="mp-adminhtml-subtitle">
                    • Ofrece todos los medios de pago.
                    <br>• Experiencia de compra en el sitio de Mercado Pago.
                    <br>• Tus clientes pueden pagar como invitados o ingresando a su cuenta de Mercado Pago.
                </span>
        </div>
        <hr class="mp-adminhtml-hr margin-top-30">
        <div class="margin-top-30">
            <span class="mp-adminhtml-title">Configuración básica:</span><br>
            <span class="mp-adminhtml-subtitle">Haz que tu cliente termine su compra de forma rápida, fácil y segura</span>
        </div>
    </td>
</tr>
