<tr>
    <td colspan="10">
        <hr class="mp-adminhtml-hr margin-top-30">
        <div class="margin-top-30">
            <span class="mp-adminhtml-title"><?php echo $helper->__('Configuración avanzada:'); ?></span><br>
            <span class="mp-adminhtml-subtitle"><?php echo $helper->__('Personaliza estas opciones y activa otras herramientas de nuestro módulo listas para usar'); ?></span>
        </div>
    </td>
</tr>
