<tr>
    <td colspan="10">
        <div class="margin-top-30">
                <span class="mp-adminhtml-subtitle">
                    • Ofrece pagos con tarjetas de débito y crédito.
                    <br>• Experiencia de pago dentro de tu tienda.
                    <br>• Tus clientes pagan como invitados sin salir de tu tienda.
                </span>
        </div>
        <hr class="mp-adminhtml-hr margin-top-30">
        <div class="margin-top-30">
            <span class="mp-adminhtml-title">Configuración básica:</span><br>
            <span class="mp-adminhtml-subtitle">Haz que tu cliente termine su compra de forma rápida, fácil y segura</span>
        </div>
    </td>
</tr>
