<tr>
    <td colspan="10">
        <div class="margin-top-30 margin-bottom-30 width-100-percent">
            <span class="mp-adminhtml-title"><?php echo $helper->__('Ingresa tus credenciales y elige cómo operar'); ?></span> <br>
            <span><?php echo $helper->__('<b>Modo Pruebas</b><br>Por defecto, te dejamos el modo Sandbox activo para que hagas testeos antes de empezar a vender. <br><br><b>Modo Producción</b> <br>Cuando veas que todo va bien, desactivá Sandbox, prendé Producción y abrí paso a tus ventas online.<br><br>'); ?></span>
        </div>
    </td>
</tr>
<?php echo $this->html_element; ?>
<tr class="margin-top-30">
    <td class="height-60 mp-adminhtl-vertical-align-center">
        <span><?php echo $helper->__('Cargar credenciales'); ?></span>
    </td>
    <td class="height-60 mp-adminhtl-vertical-align-center">
        <div class="mp-adminhtml-button-search-credentials">
            <?php echo $helper->__('Buscar mis credenciales'); ?>
        </div>
    </td>
</tr>