<tr>
    <td colspan="10">
        <div class="margin-top-30">
            <span class="mp-adminhtml-title"><?php echo $helper->__('Credenciales de Prueba'); ?></span><br>
            <span><?php echo $helper->__('Con estas claves podrás hacer las pruebas que quieras'); ?></span><br><br>
        </div>
    </td>
</tr>
<?php echo $this->html_element; ?>

<tr>
    <td colspan="10">
        <div class="margin-top-30"></div>
    </td>
</tr>
