<tr id="mp-adminhtml-cred">
    <td colspan="10">
        <div class="margin-top-30">
            <span class="mp-adminhtml-title"><?php echo $helper->__('Credenciales para producción'); ?></span><br>
            <span><?php echo $helper->__('Con estas claves podrás recibir pagos reales de tus clientes.'); ?></span><br><br>
        </div>
    </td>
</tr>
<?php echo $this->html_element; ?>

<tr>
    <td colspan="10">
        <div class="margin-top-30"></div>
    </td>
</tr>