<tr>
    <td colspan="10">
        <hr class="mp-adminhtml-hr margin-top-30">
        <div class="margin-top-30">
            <span class="mp-adminhtml-title"><?php echo $helper->__('Información básica de la tienda:'); ?></span><br>
            <span class="mp-adminhtml-subtitle"><?php echo $helper->__('Ingresa los datos de tu negocio en el módulo:'); ?></span><br><br>
        </div>
    </td>
</tr>
<?php echo $this->html_element; ?>