<tr>
    <td colspan="10">
        <div class="mp_checkout_row">
            <span class="mp-adminhtml-title"><?php echo $helper->__('Diseña la mejor experiencia de pago para tus clientes.'); ?></span>
            <img src="<?php echo $logo; ?>" class="mp_adminhtml_float_right">
        </div>

        <span class="mp-adminhtml-subtitle"> <?php echo $helper->__('Sigue estos pasos y maximiza tu conversión:'); ?> </span>

        <div class="mp_admin_row">
            <div class="mp-adminhtml-row-oval">
                <div class="mp-adminhtml-row-oval-box">
                    <div class="mp-adminhtml-oval">
                        <span class="mp-adminhtml-oval-number">1</span>
                    </div>
                    <span class="mp-adminhtml-oval-text"><?php echo $helper->__('Obtén tus <b>credenciales</b> en tu cuenta de Mercado Pago.'); ?></span>
                </div>

                <div class="mp-adminhtml-row-oval-box">
                    <div class="mp-adminhtml-oval">
                        <span class="mp-adminhtml-oval-number">2</span>
                    </div>
                    <span class="mp-adminhtml-oval-text"><?php echo $helper->__('Elige los <b>medios de pago</b> disponibles en tu tienda.'); ?></span>
                </div>

                <div class="mp-adminhtml-row-oval-box">
                    <div class="mp-adminhtml-oval">
                        <span class="mp-adminhtml-oval-number">3</span>
                    </div>
                    <span class="mp-adminhtml-oval-text"><?php echo $helper->__('Deja activo <b>‘Pruebas’</b> para testear compras en tu tienda.'); ?></span>
                </div>

                <div class="mp-adminhtml-row-oval-box">
                    <div class="mp-adminhtml-oval">
                        <span class="mp-adminhtml-oval-number">4</span>
                    </div>
                    <span class="mp-adminhtml-oval-text"><?php echo $helper->__('Homologa tu cuenta para poder cobrar.'); ?></span>
                </div>

                <div class="mp-adminhtml-row-oval-box">
                    <div class="mp-adminhtml-oval">
                        <span class="mp-adminhtml-oval-number">5</span>
                    </div>
                    <span class="mp-adminhtml-oval-text"><?php echo $helper->__('Desactiva ‘Pruebas’ solo cuando veas que todo va bien y ¡empieza a recibir pagos!'); ?></span>
                </div>
            </div>
        </div>

        <div class="mp_admin_row">
            <div class="mp-adminhtml-config-row">
                <span>
                <?php echo $helper->__('Las credenciales son las claves que te proporcionamos para que integres de forma rápida y segura.<br>Debes tener una cuenta homologada en Mercado Pago para cobrar en tu sitio web. No necesitas saber diseñar o programar para activarnos en tu tienda.'); ?>
                </span>
            </div>
        </div>

        <div class="mp_admin_row">
            <hr class="mp-adminhtml-hr">
        </div>

    </td>
</tr>
