<span class="mp-adminhtml-title">Diseña la mejor experiencia de pago para tus clientes.</span><br>
<span class="mp-adminhtml-subtitle">Sigue estos pasos y maximiza tu conversión: </span>

<div class="mp-adminhtml-row-oval">
    <div class="mp-adminhtml-row-oval-box">
        <div class="mp-adminhtml-oval">
            <span class="mp-adminhtml-oval-number">1</span>
        </div>
        <span class="mp-adminhtml-oval-text">Obtén tus credenciales en tu cuenta de Mercado Pago.</span>
    </div>

    <div class="mp-adminhtml-row-oval-box">
        <div class="mp-adminhtml-oval">
            <span class="mp-adminhtml-oval-number">2</span>
        </div>
        <span class="mp-adminhtml-oval-text">Elige los medios de pago disponibles en tu tienda.</span>
    </div>

    <div class="mp-adminhtml-row-oval-box">
        <div class="mp-adminhtml-oval">
            <span class="mp-adminhtml-oval-number">3</span>
        </div>
        <span class="mp-adminhtml-oval-text">Deja activo ‘Pruebas’ para testear compras en tu tienda.</span>
    </div>

    <div class="mp-adminhtml-row-oval-box">
        <div class="mp-adminhtml-oval">
            <span class="mp-adminhtml-oval-number">4</span>
        </div>
        <span class="mp-adminhtml-oval-text">Homologa tu cuenta para poder cobrar.</span>
    </div>

    <div class="mp-adminhtml-row-oval-box">
        <div class="mp-adminhtml-oval">
            <span class="mp-adminhtml-oval-number">5</span>
        </div>
        <span class="mp-adminhtml-oval-text">Desactiva ‘Pruebas’ solo cuando veas que todo va bien y ¡empieza a recibir pagos!</span>
    </div>
</div>

<div class="mp-adminhtml-config-row">
    <div class="mp-adminhtml-config-textarea">
        <span>
        Las credenciales son las claves que te proporcionamos para que integres de forma rápida y segura. <br>Debes tener una cuenta homologada en Mercado Pago para cobrar en tu sitio web. No necesitas saber diseñar o programar para activarnos en tu tienda.
        </span>
    </div>

</div>

<hr class="mp-adminhtml-hr">