<tr>
    <td colspan="10">
        <hr class="mp-adminhtml-hr">
    </td>
</tr>

<tr>
    <td colspan="10">
        <div class="mp-adminhtml-title">
            <?php echo $helper->__('¿Todo listo para el despegue de tus ventas?'); ?>
        </div>
    </td>
</tr>
<tr>
    <td colspan="10">
        <div class="mp-adminhtml-subtitle margin-top-30">
            <?php echo $helper->__('Visita tu tienda como si fueras uno de tus cliente y revisa que todo esté bien. 
            Si ya saliste a Producción, trae a tus clientes y aumenta tus ventas con la mejor experiencia de compra online.'); ?>
        </div>
    </td>
</tr>
<tr>
    <td colspan="10">
        <div class="mp-adminhtml-button-search-credentials margin-top-30">
            <?php echo $helper->__('Quiero testear mis ventas'); ?>
        </div>
    </td>
</tr>